language: python
sudo: False
install:
  - "pip install tox"
script:
  - "tox"
env:
  - "TOXENV=py35-1.11.X"
  - "TOXENV=py35-1.10.X"
  - "TOXENV=py35-1.9.X"
  - "TOXENV=py311-1.8.X"
  - "TOXENV=py311-1.7.X"
  - "TOXENV=py311-1.6.X"
  - "TOXENV=py311-1.5.X"
